# .pre-commit-config.yaml

repos:
  # Ruff for linting and import sorting (with auto-fix enabled)
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: ["--fix"]

  # Black for Python code formatting
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black

  # Pre-commit hooks to handle whitespace, end-of-file, and large file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files

    # Rustfmt for Rust code formatting
  - repo: local
    hooks:
      - id: clippy
        name: Run Clippy
        entry: bash -c 'cargo clippy -- -D warnings'
        language: system
        types: [rust]
