name: Publish and Deploy on Tag

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  publish:
    name: Publish to PyPI and crates.io
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set up Python and install build tools
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install maturin for PyPI
        run: pip install maturin

      - name: Build and publish to PyPI
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          maturin publish --non-interactive

      # Set up Rust toolchain
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish --token $CARGO_REGISTRY_TOKEN

  sphinx_docs:
    name: Deploy Sphinx Documentation
    runs-on: ubuntu-latest
    needs: [publish]

    steps:
      - uses: actions/checkout@v4

      # Set up Python and install Sphinx tools
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install Sphinx dependencies
        run: |
          pip install sphinx sphinx-rtd-theme

      - name: Build Sphinx documentation
        run: |
          cd docs
          make html

      # Deploy the generated HTML to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
